### ISSUE TITLE
Errors out with `xml-parse-tag-1: XML: (Well-Formed) Invalid character`

### ISSUE THREAD

**Issue by chookity-pokk** [rougier/notes-list#2]
I just used the example from the README and it throws the error `xml-parse-tag-1: XML: (Well-Formed) Invalid character`, and it produces an empty `notes-list`.

```
#+TITLE:    Emacs hacking
#+DATE:     2023-03-17
#+FILETAGS: HACK EMACS CODE
#+SUMMARY:  Notes about emacs hacking ideas
#+ICON:     bootstrap/journal-code
```

I am using Emacs 28.2 on EndeavorOS.

**Comment by rougier** [comment]
The bootstrap icon repoitory has changed and is has been fixed a few minutes ago (svg-lib). Can you update your svg-lib to the GitHub version and restest ? You might need to clean the svg cache directory in your .emacs directory.

**Comment by chookity-pokk** [comment]
I got version 2.6 of svg-lib, pulled this repo with the new update from a few hours ago and cleared my svg cache which seems to have fixed it. Thank you for the package and the quick help!
