### ISSUE TITLE
Can't display notes by date tag

### ISSUE THREAD

**Issue by mkmkbrs** [rougier/notes-list#4]
For some reason, I can't make notes list display and sort by the date tag (#+DATE: YYYY-MM-DD).

I've tried different options provided by the `notes-list-sort-function` but none gave desired output.

I have this line in my config.el (not sure if I set it correctly):
`(setq notes-list-sort-function #'notes-list-compare-creation-time)`

**Comment by rougier** [comment]
Can you check the variable `notes-list--notes` (using `C-h v` for example)

**Comment by mkmkbrs** [comment]
Sure:

`Value:
(((#1="FILENAME" . "/home/username/Documents/Denotes/notes-test.org")
  (#2="TITLE" . "[1][I]: Test")
  (#3="ICON" . "~/Documents/journal/dimg/2.jpg")
  (#4="TIME-CREATION" 25619 26416)
  (#5="TIME-MODIFICATION" 25633 34261 294346 956000)
  (#6="TIME-ACCESS" 25636 32238 945170 491000)
  (#7="SUMMARY" . "Test")
  (#8="TAGS" "EMACS" "HACK"))
 ((#1# . "/home/username/Documents/Denotes/notes-test-2.org")
  (#2# . "[2][I]: Test")
  (#3# . "bootstrap/journal")
  (#4# 25623 23472)
  (#5# 25633 32635 166603 578000)
  (#6# 25636 32238 848504 355000)
  (#7# . "Test")
  (#8# "emacs" "hack")))
`

**Comment by rougier** [comment]
They should have a TIME-CREATION property from the DATE properties in your notes. What are the first few lines of the first note?

**Comment by mkmkbrs** [comment]
```
#+title: [1][I]: Test
#+date: 2023-03-17
#+filetags: EMACS HACK
#+summary: Test
#+icon: ~/Documents/journal/dimg/2.jpg

Test
```

**Comment by rougier** [comment]
Can you try `M-: (org-collect-keywords '("DATE"))` in your test note buffer?

**Comment by mkmkbrs** [comment]
It gives:
`(("DATE" "2023-03-17"))`

**Comment by rougier** [comment]
Thanks. Can you try setting sorting by modification time and modify a note? Then you'll need t type "r" to update them.

**Comment by mkmkbrs** [comment]
Set `notes-list-sort-function` value to `notes-list-compare-modification-time` and made sure it is applied via `describe-variable`.

Modified note now displays new date in notes list - April 03, 2023.

`notes-list--notes` variable value is:

```
(((#1="FILENAME" . "/home/username/Documents/Denotes/notes-test.org")
  (#2="TITLE" . "[1][I]: Test")
  (#3="ICON" . "~/Documents/journal/dimg/2.jpg")
  (#4="TIME-CREATION" 25619 26416)
  (#5="TIME-MODIFICATION" 25642 44765 192854 79000)
  (#6="TIME-ACCESS" 25642 44773 116143 933000)
  (#7="SUMMARY" . "Modified")
  (#8="TAGS" "EMACS" "HACK"))
```
I then went back and changed the sort function value to `notes-list-compare-creation-time`. Then I modified the second note, and it also displays date modified despite sort function configuration.

**Comment by rougier** [comment]
Can you try:
```
(message "%s %s"
         (notes-list-compare-modification-time (nth 0 notes-list--notes)
                                               (nth 1 notes-list--notes))
         (notes-list-compare-modification-time (nth 1 notes-list--notes)
                                               (nth 0 notes-list--notes)))
```

**Comment by rougier** [comment]
Oh wait, you mean you want to have the creation date displayed instead of modification? But sorting is ok?

**Comment by mkmkbrs** [comment]
Yes, I want to see the date from the date tag displayed on the side of the note item. I don't know if sorting is ok since the displayed date is always the modification time. Sorry for being unclear the first time.

**Comment by rougier** [comment]
Ok, now I got it. The displayed date is the modified date and I don't have yet the option to display other date. I'll fix that.

**Comment by rougier** [comment]
Done. You now have a `notes-list-date-display` to choose which date to display.

**Comment by mkmkbrs** [comment]
Thanks, I can now see the appropriate date from the date tag of each note. However, using images instead of icons now gives an error and an empty notes list:

`svg-lib-icon: Wrong type argument: stringp, nil`

It would be nice to be able to sort notes by date: from newest to oldest and vice-versa. For now, it seems sorting by modification or creation time leaves the list unchanged.

**Comment by rougier** [comment]
Can you open new issues for the svg-lib-icon problem?

To sort by date newest/oldest, I'll add the option

**Comment by mkmkbrs** [comment]
> Can you open new issues for the svg-lib-icon problem?

Sure.

> To sort by date newest/oldest, I'll add the option

Thank you once again.

**Comment by mkmkbrs** [comment]
> > Can you open new issues for the svg-lib-icon problem?
> 
> Sure.
> 
> > To sort by date newest/oldest, I'll add the option
> 
> Thank you once again.

Sorry that issue was on me. I've misspelled the path to the image.

**Comment by rougier** [comment]
Just added sort order. It is boudn to "s" to reverse.
